# Generated by Django 5.2.17 on 2026-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_message_body_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='demo_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
    ]
